genai:
  lib: ollama
  ollama:
    model: deepseek-r1:7b
    base_url: http://localhost:11434

embedding:
  lib: ollama
  ollama:
    model: deepseek-r1:7b
    base_url: http://localhost:11434
